# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"<\n\x12\x43reateCheckRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x14\n\x05items\x18\x02 \x03(\x0b\x32\x05.Item\"5\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"(\n\x13\x43reateCheckResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t2H\n\x0c\x43heckService\x12\x38\n\x0b\x43reateCheck\x12\x13.CreateCheckRequest\x1a\x14.CreateCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECHECKREQUEST']._serialized_start=17
  _globals['_CREATECHECKREQUEST']._serialized_end=77
  _globals['_ITEM']._serialized_start=79
  _globals['_ITEM']._serialized_end=132
  _globals['_CREATECHECKRESPONSE']._serialized_start=134
  _globals['_CREATECHECKRESPONSE']._serialized_end=174
  _globals['_CHECKSERVICE']._serialized_start=176
  _globals['_CHECKSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
